[[plugins]]
repo = 'Shougo/dein.vim'

#
# color scheme
#
[[plugins]]
hook_add = '''
augroup SetColorScheme 
    au!
    au VimEnter * nested colorscheme iceberg
augroup END
'''
repo = 'cocopon/iceberg.vim'
# colorscheme 設定は source 後に行う必要があるので確実に読まれている VimEnter のタイミングで行う。
# 但し Colorscheme イベントの発生が抑制されないよう nented を付ける。

#
# syntax
#
[[plugins]] # toml syntax
on_ft = 'toml'
repo = 'cespare/vim-toml'

#
# File Tree
#
[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = '''
 map <C-n> :NERDTreeToggle<CR>
'''
# if you want to run NERDTree on startup nvim, comment out below.
# autocmd VimEnter * execute 'NERDTree'

#
# git
#
[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plagins]]
repo = 'tpope/vim-fugitive'

#
# not install
#
[[plagins]]
repo = 'Townk/vim-autoclose'
